CREATE TABLE stock (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_id INTEGER NOT NULL,
	amount INTEGER NOT NULL,
	best_before_date DATE,
	purchased_date DATE DEFAULT (CURRENT_DATE),
	stock_id TEXT NOT NULL,
	row_created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)
