CREATE TABLE shopping_list (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	product_id INTEGER NOT NULL UNIQUE,
	amount INTEGER NOT NULL DEFAULT 0,
	amount_autoadded INTEGER NOT NULL DEFAULT 0,
	row_created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)
