CREATE TABLE api_keys (
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	api_key varchar(30) NOT NULL UNIQUE,
	expires DATETIME,
	last_used DATETIME,
	row_created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)
